---
- name: Static Page
  hosts: g1
  become: yes

  tasks:
    - name: Update static page
      ansible.builtin.copy:
        src: files/static.html
        dest: /var/www/html/static.html
        
        

...