---
- name: Deploy Static Page
  hosts: g1
  become: yes

  tasks: 
    - name: Ensure /var/www/html exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy Static HTML File
      ansible.builtin.copy:
        src: /static.html
        dest: /var/www/html/static.html
        

...